services:
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=synoptic
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
